name: Build and Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: build and test
        run: make build

      - uses: docker/metadata-action@v5
        if: ${{ github.event_name == 'push tag' }}
        id: meta
        with:
          images: |
            ghcr.io/prantlf/litevec
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - uses: docker/login-action@v3
        if: ${{ github.event_name == 'push tag' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        if: ${{ github.event_name == 'push tag' }}
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: docker/build-push-action@v5
        if: ${{ github.event_name != 'push tag' }}
        with:
          push: false
